/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#56633b",
        "primary-container": "#8c9b6e",
        "primary-fixed": "#d9e9b6",
        "primary-fixed-dim": "#bdcd9c",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#141f01",
        "on-primary-fixed-variant": "#3e4b26",
        "on-primary-container": "#26320f",
        "secondary": "#645d56",
        "secondary-container": "#ebe1d8",
        "secondary-fixed": "#ebe1d8",
        "secondary-fixed-dim": "#cec5bc",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#1f1b16",
        "on-secondary-fixed-variant": "#4c463f",
        "on-secondary-container": "#6a635c",
        "tertiary": "#7d525f",
        "tertiary-container": "#b98896",
        "tertiary-fixed": "#ffd9e2",
        "tertiary-fixed-dim": "#eeb8c7",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#30111c",
        "on-tertiary-fixed-variant": "#623b47",
        "on-tertiary-container": "#46232e",
        "background": "#fcf9f8",
        "on-background": "#1b1c1c",
        "surface": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-variant": "#e4e2e1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e4e2e1",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#45483e",
        "outline": "#76786d",
        "outline-variant": "#c6c8ba",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0f0",
        "inverse-primary": "#bdcd9c",
        "surface-tint": "#56633b",
      },
    },
  },
  plugins: [],
}

